# Generated by Django 3.2.4 on 2021-12-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='populacao',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
